project_id = "jlndohflirfixbinqdwe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableapp.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
enable_phone_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
s3_max_part_size = "5MiB"

[edge_functions]
enabled = true
port = 54323

[functions.tripletex-api]
verify_jwt = false

[functions.nightly-sync]
verify_jwt = false

[functions.calendar-sync]
verify_jwt = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15