project_id = "jlndohflirfixbinqdwe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableapp.com"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
file_size_limit = "50MiB"


[functions.tripletex-api]
verify_jwt = false

[functions.nightly-sync]
verify_jwt = true

[functions.calendar-sync]
verify_jwt = true

[db]
shadow_port = 54320
major_version = 17