// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env, isDevelopment } from '@/lib/env';

const SUPABASE_URL = env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const isBrowser = typeof window !== "undefined";

// Enhanced validation for browser environment
if (isBrowser && isDevelopment) {
  // Additional browser-specific validation in development
  if (!SUPABASE_URL || SUPABASE_URL.includes('placeholder')) {
    console.warn('⚠️ Supabase URL appears to be a placeholder. Please check your .env.local file.');
  }
  
  if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('placeholder')) {
    console.warn('⚠️ Supabase key appears to be a placeholder. Please check your .env.local file.');
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
