// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-key';

const isBrowser = typeof window !== "undefined";

// Validate environment variables at runtime (not build time)
if (isBrowser && process.env.NEXT_PUBLIC_SUPABASE_URL === undefined) {
  console.error("Missing Supabase environment variable NEXT_PUBLIC_SUPABASE_URL. Set it in your environment configuration.");
}

if (isBrowser && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY === undefined) {
  console.error("Missing Supabase environment variable NEXT_PUBLIC_SUPABASE_ANON_KEY. Set it in your environment configuration.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
